//Generated by XOR-Memory Generator
//LICENSED for use by https://github.com/aaqdas
module xor_4r_2w_tb;
reg clk;
reg [1:0] i_enW;
reg [(10-1):0] i_ra1;
wire [(32-1):0] o_r1;
reg [(10-1):0] i_ra2;
wire [(32-1):0] o_r2;
reg [(10-1):0] i_ra3;
wire [(32-1):0] o_r3;
reg [(10-1):0] i_ra4;
wire [(32-1):0] o_r4;
reg [(10-1):0] i_wa1;
reg [(32-1):0]    i_w1;
reg [(10-1):0] i_wa2;
reg [(32-1):0]    i_w2;
xor_4r_2w uut(
.clk(clk)
,.i_enW(i_enW)
,.i_ra1(i_ra1)
,.o_r1(o_r1)
,.i_ra2(i_ra2)
,.o_r2(o_r2)
,.i_ra3(i_ra3)
,.o_r3(o_r3)
,.i_ra4(i_ra4)
,.o_r4(o_r4)
,.i_wa1(i_wa1)
,.i_w1(i_w1)
,.i_wa2(i_wa2)
,.i_w2(i_w2)
);
initial clk = 0;
always #10 clk = ~clk;

initial
begin
i_enW = 2'b00;
i_wa1 = 0;
i_w1  = 0;
i_wa2 = 0;
i_w2  = 0;
i_ra1 = 0;
i_ra2 = 0;
i_ra3 = 0;
i_ra4 = 0;
#10;
i_enW = 2'b11;
i_wa1 = 868;
i_w1  = 2826697867;
i_wa2 = 413;
i_w2  = 3512928524;
#10;
i_wa1 = 14;
i_w1  = 924560399;
i_wa2 = 969;
i_w2  = 315016303;
#20;
i_enW = 2'b00;
i_ra1 = 868;
i_enW = 2'b00;
i_ra2 = 413;
i_enW = 2'b00;
i_ra3 = 14;
i_enW = 2'b00;
i_ra4 = 969;
end
endmodule