//Generated by XOR-Memory Generator
//LICENSED for use by https://github.com/aaqdas
module xor_4r_4w_tb;
reg clk;
reg [3:0] i_enW;
reg [(10-1):0] i_ra1;
wire [(32-1):0] o_r1;
reg [(10-1):0] i_ra2;
wire [(32-1):0] o_r2;
reg [(10-1):0] i_ra3;
wire [(32-1):0] o_r3;
reg [(10-1):0] i_ra4;
wire [(32-1):0] o_r4;
reg [(10-1):0] i_wa1;
reg [(32-1):0]    i_w1;
reg [(10-1):0] i_wa2;
reg [(32-1):0]    i_w2;
reg [(10-1):0] i_wa3;
reg [(32-1):0]    i_w3;
reg [(10-1):0] i_wa4;
reg [(32-1):0]    i_w4;
xor_4r_4w uut(
.clk(clk)
,.i_enW(i_enW)
,.i_ra1(i_ra1)
,.o_r1(o_r1)
,.i_ra2(i_ra2)
,.o_r2(o_r2)
,.i_ra3(i_ra3)
,.o_r3(o_r3)
,.i_ra4(i_ra4)
,.o_r4(o_r4)
,.i_wa1(i_wa1)
,.i_w1(i_w1)
,.i_wa2(i_wa2)
,.i_w2(i_w2)
,.i_wa3(i_wa3)
,.i_w3(i_w3)
,.i_wa4(i_wa4)
,.i_w4(i_w4)
);
initial clk = 0;
always #10 clk = ~clk;

initial
begin
i_enW = 4'b1111;
i_wa1 = 857;
i_w1  = 514574407;
i_wa2 = 983;
i_w2  = 3240788856;
i_wa3 = 747;
i_w3  = 3147484099;
i_wa4 = 473;
i_w4  = 3057069754;
#20;
i_enW = 4'b0000;
i_ra1 = 857;
i_enW = 4'b0000;
i_ra2 = 983;
i_enW = 4'b0000;
i_ra3 = 747;
i_enW = 4'b0000;
i_ra4 = 473;
end
endmodule